apiVersion: v1
kind: Service
metadata:
  name: kubeusers-service
spec:
  selector:
    app: kubeusers
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007  # Puedes cambiarlo por otro número en el rango 30000-32767
  type: NodePort  # LoadBalancer no funciona en Minikube sin túnel

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubedeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:  # Corrección de indentación
        - name: kubecontainer
          image: maxirosanda/recursos-backend:1.0.0
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: "mongodb+srv://maxirosanda:PvG6lFw1PQKtDHwU@cluster0.wh168.mongodb.net/recursos-backend?retryWrites=true&w=majority&appName=Cluster0"
          imagePullPolicy: Always

